#!/bin/bash -e

echo -e "\nWelcome to Engage! There are a ton of tools in this container and echo-server is running so \"curl locahost\" for some quick details. \nMore details here: https://github.com/InAnimaTe/docker-engage"

# Consume a different ssh port, or use the default.
SSHPORT=${SSHPORT:-22}

## Set up user desired timezone
if [ -n "$TZ" ] && [ -f "/usr/share/zoneinfo/$TZ" ]; then
  ln -sf "/usr/share/zoneinfo/$TZ" /etc/localtime
  echo "$TZ" > /etc/timezone
else
  echo "Warning: Invalid or missing TZ. Defaulting to UTC."
fi

## Dropuser setup
# Check if the required environment variables are defined
if [ -n "${DROPUSER}" ] && [ -n "${DU_UID}" ] && [ -n "${DU_GID}" ]; then
  # Use DROPGROUP if set; otherwise, default to DROPUSER as the group name.
  GROUPNAME="${DROPGROUP:-$DROPUSER}"
  
  echo "Creating group '${GROUPNAME}' with GID ${DU_GID}..."
  groupadd -g "${DU_GID}" "${GROUPNAME}"
  
  echo "Creating user '${DROPUSER}' with UID ${DU_UID}, primary GID ${DU_GID}, setting shell to /bin/zsh and not creating a home directory..."
  useradd -N -M -u "${DU_UID}" -g "${DU_GID}" -s /bin/zsh "${DROPUSER}"

  echo "Setting dropuser password to ensure they are not locked.."
  DROPUSERPASSWORD="${DU_PASS:-engage}"
  echo -e "${DROPUSERPASSWORD}\n${DROPUSERPASSWORD}" | passwd ${DROPUSER}

  # Grant the dropuser sudo privileges without a password
  echo "Enabling the user to use sudo and su as root.."

  echo "${DROPUSER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DROPUSER}
  chmod 0440 /etc/sudoers.d/${DROPUSER}
  chmod 4755 $(which su)
fi

## Loopmode check and execute if desired
if [ "$LOOPMODE" ] && [ $LOOPINTERVAL ]; then
    echo ">> Entering LoopMode with interval $LOOPINTERVAL..."
    while true
    do
        echo ">> Running given command..."
        bash -x -c "$@"
        echo ">> Beginning Sleep Internval for $LOOPINTERVAL ..."
        sleep $LOOPINTERVAL
    done
else
    echo -e "\nStarting given command $@ now!\n"
    ### Blast-off!
    bash -x -c "$@"
fi
