#!/bin/bash

echo -e "\nWelcome to Engage! There are a ton of tools in this container and echo-server is running so \"curl locahost\" for some quick details. \nMore details here: https://github.com/InAnimaTe/docker-engage"
echo -e "\nStarting $@ now!\n"

# Blast-off!
bash -x -c "$@"
